public class ExcessiveParameterListTrigger {
    // This class is generated to trigger the rule: sf:ExcessiveParameterList
    // Rule: Excessive Parameter List
    public void triggerRule(Integer one, Integer two, Integer three, Integer four, Integer five, Integer six, Integer seven, Integer eight, Integer nine, Integer ten, Integer eleven, Integer twelve, Integer thirteen, Integer fourteen, Integer fifteen, Integer sixteen, Integer seventeen, Integer eighteen, Integer nineteen, Integer twenty) {
        System.debug('This class triggers: sf:ExcessiveParameterList');
    }
}