public class LeftBracesSpacingPositionsTrigger {
    // This class is generated to trigger the rule: sf:LeftBracesSpacingPositions
    // Rule: Left Braces Spacing Should Be Consistent
    public void triggerRule() {
        System.debug('This class triggers: sf:LeftBracesSpacingPositions');
    }

    public void test1(){
        // This is an example of no spaces. (Class parameter set to None)
    }
    public void test2() {
        // This is an example of a single space. (Class parameter set to Single)
    }
}